credentials:
  usernames:
    admin:
      email: camara@protonmail.com
      name: Admin
      password: $2b$12$Khaku0zgyPeS1Ljo7MnMAeNDk4m4tTpzbNgH6SWspdUg7ARxjtaLy
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - camara@protonmail.com
